name: CI/CD for Turborepo

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            turbo-${{ runner.os }}-

  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Restore dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn turbo run lint

      - name: Run format check
        run: yarn turbo run format

  build:
    name: Build applications
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Restore dependencies
        run: yarn install --frozen-lockfile

      - name: Build Client
        run: yarn turbo run build --filter=client

      - name: Build Admin
        run: yarn turbo run build --filter=admin

  deploy-client:
    name: Deploy Client
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Client
        run: |
          echo "Deploying client..."
          # Thêm lệnh deploy tương ứng, ví dụ: scp, rsync, hoặc Vercel

  deploy-admin:
    name: Deploy Admin
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Admin
        run: |
          echo "Deploying admin..."
          # Thêm lệnh deploy tương ứng, ví dụ: scp, rsync, hoặc Vercel
